### ISSUE TITLE
nCr and nPr built-in function overloads

### ISSUE THREAD

**Issue by JohannesMP** [ovk/clcalc#1]
Currently 'combinations' is the longest function (12 characters) mentioned in the list of most common [built-in functions in the clcalc docs](https://clcalc.net/help.html#mathjs-builtin-functions)

`nCr(n, k)` is a pretty common function name used for `combinations(n, k)`. Similarly with `nPr(n, k)` for `permutations(n, k)`, for example in Texas Instruments Calculators.

It would be convenient if such overloads could be added as native built-in function overloads, and I don't think that these names would ever conflict with anything.

----

I concede that this is pretty low priority, since it is possible to [define custom functions](https://clcalc.net#eyJjIjpbIm5DcihuLGspwqA9wqBjb21iaW5hdGlvbnMobixrKSIsIm5QcihuLGspwqA9wqBwZXJtdXRhdGlvbnMobixrKSIsIm5Dcig1LDQpIiwiblByKDUsNCkiXSwidiI6IjEifQ==):
```
> nCr(n,k) = combinations(n,k)
> nPr(n,k) = permutations(n,k)
> nCr(5,4)
   5
> nPr(5,4)
   120
```

I would also understand if, since the built-in math functions are bound to those found in [mathjs](http://mathjs.org/docs/reference/functions.html), that you may prefer to not add your own additional overloads.  

I only bring it up since, unlike other long function like [`setSymDifference`](http://mathjs.org/docs/reference/functions/setSymDifference.html), `combinations` is specifically mentioned as one of the most commonly used functions in the [built-in function documentation](https://clcalc.net/help.html#mathjs-builtin-functions), and I feel users would really benefit from such a convenient native overload.

[Game designers](https://www.reddit.com/7q6hjx/) especially would benefit from this, since it would make probability calculations far less verbose.

**Comment by ovk** [comment]
Thanks for the suggestion @JohannesMP. I'll add these aliases in next update.
Meanwhile you can take advantage of autocompletion. For example, if you type `comb` and press TAB key it will be completed to `combinations`.
