### ISSUE TITLE
Make it easier to copy result values

### ISSUE THREAD

**Issue by JohannesMP** [ovk/clcalc#2]
A small quality of life request: It would be really convenient if we could select output using the mouse cursor.

Currently it is not possible to select and copy the only one displayed output line of an expression without using TeX pretty-printing.

Since the expressions themselves can be selected, one workaround currently is to start the selection in the expression above the desired output, and drag the selection to the expression below the desired output. While the output line won't be highlighted, performing the copy operation will include the output.

---

For example,suppose the user wants to copy the `3` output here:
![](https://i.imgur.com/DkGfh7Y.png)

If they drag the above selection and then do `ctrl+C` (or your OS equivalent), it will result in this copied output:
```
+2
3
>4
```

Even though the user is unable to just select the `3` output.

While workable, this is really not an ideal solution, since it always requires the user to manually remove the undesired top/bottom fragments.

---

Alternatively, just clicking a given line could copy the contained output to the clipboard, but that might lend itself to accidentally copying by clicking unintentionally. 

Maybe a copy button all the way on the right side of the console. It could just use the clipboard icon and be mostly greyed out unless the user mouses over it.

**Comment by ovk** [comment]
Could you please post browser name and version  where this is reproducible? Seems to be working fine for me, so it is most likely an issue with specific browser.

**Comment by JohannesMP** [comment]
Chrome 64 for windows (standard install, auto-updated to: 63.0.3239.132):

![clcalc](https://user-images.githubusercontent.com/662874/35032341-74bc2374-fb1b-11e7-8672-46e4a64c987b.gif)

**Comment by ovk** [comment]
Confirmed the issue with Chrome. The selection is blocked due to improper `user-select` property set by jquery.terminal library. Hopefully should be resolved soon.
