### ISSUE TITLE
Option to increase readability of long numbers

### ISSUE THREAD

**Issue by JohannesMP** [ovk/clcalc#3]
It can be hard to read long outputs, such as if you want to enter them on another device and cannot copy the value directly (see also #2 ).

For example, if I want to write this output down:
![](https://i.imgur.com/lWdlcoR.png)

It can be really hard to read without digit separators.

If clcalc had an option to passively injected digit separators (so they wouldn't be included if the output was copied), it would be far more readable. For example (browser inspector mockup):
![](https://i.imgur.com/qPjD7is.png)

The formatting could be tweaked so that the spacing doesn't change. For example (Photoshop mockup):
![](https://i.imgur.com/0vprDlt.png)

Or potentially a combination of both of these approaches (a small gap, with an overlaid divider).

**Comment by ovk** [comment]
Thanks, that's a useful suggestion. Having separators optional and configurable could certainly improve readability.
I'll have to think about the best way to implement it.

**Comment by JohannesMP** [comment]
Now that I think about it, you might even be able to get away without using dividing characters at all, and simply adjusting the spacing of every 3rd character (assuming the setting is enabled) might be enough.

For example, here's another Photoshop Mockup, this time just adding an extra 5 pixel gap:
![](https://i.imgur.com/b7u4iIh.png)

I think this may be the cleanest visually, and also gets around the potential confusion for languages that write `1.234.567,890` instead of `1,234,567.890`

**Comment by JohannesMP** [comment]
I threw together a quick mockup of one way this could be done: http://jsfiddle.net/x3u56aga/ - Hit run and the numbers will get be spaced out, `|` bars included to clearly show boundaries.

Basically given a number string, it injects a custom `<num-gap></num-gap>` tag (could of course be a span with a class too if preferred) every 3 digits and that tag has a small amount of padding (used `0.3em` just so it was obvious).

This can probably be optimized (not sure if there any better string manipulation tricks I'm missing) but it demonstrates the property that the text is unmodified when selected and copied by the user.

**Comment by ovk** [comment]
Agree, using spacing for separation is probably better. No issues with filtering out separator characters during selection, no need to worry about internationalization. And is even looks cleaner that using coma or dot as a separator character.
