### ISSUE TITLE
Support for ln()

### ISSUE THREAD

**Issue by ubercorb77** [ovk/clcalc#33]
I can't use ln() function. I love this calculator, that is the only thing I am missing.

**Comment by ovk** [comment]
You can use `log` function for a natural logarithm. It has two forms: when called with one argument, it behaves as a natural logarithm, for example [log(e)](https://clcalc.net#eyJjIjpbImxvZyhlKSJdLCJ2IjoiMSJ9); when called with two arguments, it calculates a logarithm in a given base, e.g. [log(4, 2)](https://clcalc.net#eyJjIjpbImxvZyg0LMKgMikiXSwidiI6IjEifQ==). 
Please see more in [help(log)](https://clcalc.net#eyJjIjpbImhlbHAobG9nKSJdLCJ2IjoiMSJ9).

But I agree, `ln()` is a very common convention for a natural logarithm, so I'll add it as an alias.
