### ISSUE TITLE
Automatically put last result into a special var?

### ISSUE THREAD

**Issue by mnpenner** [ovk/clcalc#4]
Can you put the result of the last equation into a special var like `ans` or `result` or `_` or `$` or something?

e.g.

```
> 5*2
10
> ans*3
30
```

**Comment by ovk** [comment]
It is not currently possible to get the value of the last evaluated expression via some built-in variable. 
I can certainly see why it could be useful, so I may try to add such variale in the future. Or if anyone else wants to do it PRs are more than welcome.

Meanwhile, you can press `Up` arrow key to get the last command.

**Comment by ovk** [comment]
The description available in the help section: https://clcalc.net/help.html#last-evaluated-expression
