### ISSUE TITLE
Scientific Notation

### ISSUE THREAD

**Issue by Chris-toph** [ovk/clcalc#66]
Hello,
Thank to provide this nice online calculator.
To me one basic feature would be to have the option to display the numbers in scientific notation, i.e. 0.12345678E-27.
It is so common, I don't get how it was not included by default. 
Regards,
C.

**Comment by ovk** [comment]
You can use number literals in scientific notation, for example: [0.12345678E-27](https://clcalc.net#eyJjIjpbIi4xMjM0NTY3OEUtMjciXSwidiI6IjEifQ==).
Or did you mean something like an option in settings to display all numbers in this format?

**Comment by Chris-toph** [comment]
Yes, I mean to display the numbers in scientific notation.

**Comment by ovk** [comment]
You can use existing MathJS [format](https://mathjs.org/docs/reference/functions/format.html) function to format numbers in desired format, for example:

```
format(120000, { notation: "exponential" })
```
(try it [here](https://clcalc.net#eyJjIjpbImZvcm1hdCgxMjAwMDAswqB7wqBub3RhdGlvbjrCoFwiZXhwb25lbnRpYWxcIsKgfSkiXSwidiI6IjEifQ==))

Or you could define a simple function to make it less verbose:

```
toexp(n) = format(n, { notation: "exponential" })
```
(try it [here](https://clcalc.net#eyJjIjpbInRvZXhwKG4pwqA9wqBmb3JtYXQobizCoHvCoG5vdGF0aW9uOsKgXCJleHBvbmVudGlhbFwiwqB9KSIsInRvZXhwKDEyMDApIl0sInYiOiIxIn0=))

This is obviously not very convenient, so I added new setting `Output Number Format` that allows to select desired number format:

![image](https://user-images.githubusercontent.com/693072/152659926-05055361-2ff3-4e04-b22e-5d5e3197b789.png)

**Comment by Chris-toph** [comment]
Hello, 
Thanks for having implement a such of feature. But sorry, to me there is one feature which is not so much meaningful is your setting _Precision (Significant Digits)_ . In general one needs always the maximum precision but it should not be mixed with the display digits. 
Eg.: if you set the precision to 8 and then calculate pi*1e12 = 3141592700000. 
To me, your precision setting should be replaced by number of displayed digits as all calculators do!
Regards,
C.

**Comment by ovk** [comment]
The precision comes from the underlying [decimal.js](https://mikemcl.github.io/decimal.js/#precision) library and it's not related to how many digits are displayed. All calculators have precision limits, one way or another, as computer memory is finite. Precision limits usually expressed in significant digits or underlying data type size and are not related to how a number will be eventually formatted. So the precision only affects display digits indirectly - it allows to have larger (or smaller) numbers that just take more digits to represent.

But I think I understand your point: it may indeed be beneficial to have high precision but without numbers that take half of the screen when formatted exactly. This can be done now with the `format` function, but I'll try to add "formatting precision" as a setting later.
